const data = {
  products: [
    {
      name: 'Airpod',
      slug: 'airpod',
      category: 'Earpod',
      image: '/images/airpods.png',
      price: 500,
      brand: 'apple',
      rating: 4.5,
      numReview: 8,
      countInStock: 5,
      description: 'A popular Earpod',
    },
    {
        name: 'Freebud',
        slug: 'freebud',
        category: 'Earpod',
        image: '/images/freebuds.png',
        price: 500,
        brand: 'Oraimo',
        rating: 4.5,
        numReview: 8,
        countInStock: 20,
        description: 'A popular Earpod',
      },
    {
        name: 'Samsung Galaxy',
        slug: 'samsung-galaxy',
        category: 'Phones',
        image: '/images/galaxy.png',
        price: 400,
        brand: 'Samsung',
        rating: 3.2,
        numReview: 10,
        countInStock: 20,
        description: 'A popular Phone',
      },
      {
        name: 'Headset',
        slug: 'headset',
        category: 'Headset',
        image: '/images/headset.png',
        price: 350,
        brand: 'JBL',
        rating: 3.2,
        numReview: 3,
        countInStock: 70,
        description: 'A popular Headset',
      },
      {
        name: 'Macbook Air 2015',
        slug: 'mackbook-air-2015',
        category: 'Laptop',
        image: '/images/macbook.png',
        price: 350,
        brand: 'Apple',
        rating: 3.2,
        numReview: 3,
        countInStock: 70,
        description: 'A popular Laptop',
      },
      {
        name: 'MSI',
        slug: 'msi',
        category: 'Laptop',
        image: '/images/msi.png',
        price: 350,
        brand: 'MSI',
        rating: 3.2,
        numReview: 3,
        countInStock: 70,
        description: 'A popular Laptop',
      },
      {
        name: 'ROG',
        slug: 'rog',
        category: 'Laptop',
        image: '/images/rog.png',
        price: 350,
        brand: 'ROG',
        rating: 3.2,
        numReview: 3,
        countInStock: 70,
        description: 'A popular Laptop',
      },
      {
        name: 'Iphone 13',
        slug: 'iphone-13',
        category: 'Phones',
        image: '/images/iphone.png',
        price: 350,
        brand: 'Apple',
        rating: 3.2,
        numReview: 3,
        countInStock: 70,
        description: 'A popular phone',
      },
      {
        name: 'Redmi 14',
        slug: 'redmi-24',
        category: 'Phones',
        image: '/images/redmi.png',
        price: 350,
        brand: 'Redmi',
        rating: 3.2,
        numReview: 3,
        countInStock: 70,
        description: 'A popular phone',
      },
  ],
};

export default data